# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  release:
    types: 
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'

    - name: install packages
      run: npm install
    
    - name: testing 
      run: echo $GITHUB_REF
        
