name: CI

on:
  release:
    types: 
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
        
    - name: install packages
      run: npm install
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    
    - name: testing 
      run: echo ${{ steps.get_version.outputs.VERSION }}
      
    - name: upload the build file to twilio to host
      env:
        TWILIO_ACCOUNT_SID: $secrets.TWILIO_ACCOUNT_SID
        TWILIO_AUTH_TOKEN: $secrets.TWILIO_AUTH_TOKEN
      run: npm run deploy custom ${{ steps.get_version.outputs.VERSION }} -- --pilot-plugins-api
      
    - name: set that there is a new version in the plugins api
      uses: wei/curl@v1.1.1
      env: 
        PLUGIN_NAME: test1
        PLUGIN_PROJECT_NAME: plugin-test1
        RUNTIME_DOMAIN: default-1074-nbd21.twil.io
      with:
        args: https://flex-api.twilio.com/v1/PluginService/Plugins/$env.PLUGIN_NAME/Versions -d Version=${{ steps.get_version.outputs.VERSION }} -d PluginUrl="https://$env.RUNTIME_DOMAIN/plugins/$env.PLUGIN_PROJECT_NAME/${{ steps.get_version.outputs.VERSION }}/bundle.js" -d Changelog="here's my version" -d Private=true -u $secrets.TWILIO_ACCOUNT_SID:$secrets.TWILIO_AUTH_TOKEN
        
