name: CI

# Controls when the action will run. 
on:
  release:
    types: 
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - env: 
        PLUGIN_NAME: test1
        PLUGIN_PROJECT_NAME: plugin-test1
        RUNTIME_DOMAIN: default-1074-nbd21.twil.io
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
        
    - name: install packages
      run: npm install
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    
    - name: testing 
      run: echo ${{ steps.get_version.outputs.VERSION }}
      
    - name: upload the build file to twilio to host
      run: npm run deploy custom ${{ steps.get_version.outputs.VERSION }} -- --pilot-plugins-api
      
    - name: set that there is a new version in the plugins api
      uses: wei/curl@v1.1.1
      with:
        args: https://flex-api.twilio.com/v1/PluginService/Plugins/$env.PLUGIN_NAME/Versions -d Version=${{ steps.get_version.outputs.VERSION }} -d PluginUrl="https://$env.RUNTIME_DOMAIN/plugins/$env.PLUGIN_PROJECT_NAME/${{ steps.get_version.outputs.VERSION }}/bundle.js" -d Changelog="here's my version" -d Private=true -u $secrets.TWILIO_ACCOUNT_SID:$secrets.TWILIO_AUTH_TOKEN
        
